version: '3.4'

services:
  telegramauctionbot:
    image: telegramauctionbot
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
  telegrambotapi:
    image: telegrambotapi
    build:
      context: ./db_api
      dockerfile: ./Dockerfile_api
    env_file:
      - .env
    volumes:
      - ./data_base/sql_app.db:/app/data_base/sql_app.db
    ports:
      - ${PORT:-8001}:${PORT:-8001}
